/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Chambered API
 * An OData and version-compliant API for Chambered inventory tracking.
 * OpenAPI spec version: 1.0
 */

/**
 * Data transfer object defining Apprise push notification properties.
 */
export interface AppriseSettingsResponseDto {
  /** Indicates whether self-signed SSL certs are trusted. */
  allowInvalidCertificates?: boolean;
  /**
     * The push notification server URL.
     * @nullable
     */
  hostUrl?: string | null;
  /**
     * The secret Apprise decryption key.
     * @nullable
     */
  notificationKey?: string | null;
  /**
     * The delivery endpoints payload.
     * @nullable
     */
  targetUrls?: string | null;
  /** The connection timeout parameter. */
  timeoutSeconds?: number;
}
