/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Chambered API
 * An OData and version-compliant API for Chambered inventory tracking.
 * OpenAPI spec version: 1.0
 */

export interface AppriseSettingsResponseDto {
  allowInvalidCertificates?: boolean;
  /** @nullable */
  hostUrl?: string | null;
  /** @nullable */
  notificationKey?: string | null;
  /** @nullable */
  targetUrls?: string | null;
  timeoutSeconds?: number;
}
