/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Chambered API
 * An OData and version-compliant API for Chambered inventory tracking.
 * OpenAPI spec version: 1.0
 */
import type { ArmoryItem as __ArmoryItem } from './armoryItem';
import type { Arsenal } from './arsenal';
import type { ChamberedUser } from './chamberedUser';
import type { ItemCondition } from './itemCondition';
import type { Product } from './product';
import type { Vault } from './vault';

export interface ArmoryItem {
  id?: number;
  /** @nullable */
  itemType?: string | null;
  productId?: number;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  purchasePrice?: number | null;
  /** @nullable */
  purchaseDate?: string | null;
  /** @nullable */
  estimatedValue?: number | null;
  condition?: ItemCondition;
  /** @nullable */
  ownerId?: string | null;
  owner?: ChamberedUser;
  /** @nullable */
  beneficiaryId?: string | null;
  /** @nullable */
  vaultId?: number | null;
  vault?: Vault;
  /** @nullable */
  arsenalId?: number | null;
  /** @nullable */
  parentItemId?: number | null;
  /** @nullable */
  imageUrl?: string | null;
  /** @nullable */
  notesMarkdown?: string | null;
  product?: Product;
  beneficiary?: ChamberedUser;
  arsenal?: Arsenal;
  parentItem?: __ArmoryItem;
  /** @nullable */
  mountedAccessories?: ArmoryItem[] | null;
}
