/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Chambered API
 * An OData and version-compliant API for Chambered inventory tracking.
 * OpenAPI spec version: 1.0
 */

export type ArmoryItemDocumentType = typeof ArmoryItemDocumentType[keyof typeof ArmoryItemDocumentType];


export const ArmoryItemDocumentType = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
} as const;
