/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Chambered API
 * An OData and version-compliant API for Chambered inventory tracking.
 * OpenAPI spec version: 1.0
 */
import type { ArmoryItem } from './armoryItem';
import type { ChamberedUser } from './chamberedUser';
import type { Vault } from './vault';

export interface Arsenal {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  iconName?: string | null;
  /** @nullable */
  colorHex?: string | null;
  id?: number;
  /** @nullable */
  created?: string | null;
  /** @nullable */
  modified?: string | null;
  /** @nullable */
  createdBy?: string | null;
  /** @nullable */
  modifiedBy?: string | null;
  /** @nullable */
  users?: ChamberedUser[] | null;
  /** @nullable */
  vaults?: Vault[] | null;
  /** @nullable */
  armoryItems?: ArmoryItem[] | null;
}
