/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Chambered API
 * An OData and version-compliant API for Chambered inventory tracking.
 * OpenAPI spec version: 1.0
 */

export interface AuthenticationResponseDto {
  /** @nullable */
  userId?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  accessToken?: string | null;
  /** @nullable */
  refreshToken?: string | null;
  expiresInSeconds?: number;
  /** @nullable */
  roles?: string[] | null;
  /** @nullable */
  permissions?: string[] | null;
  /** @nullable */
  username?: string | null;
  /** @nullable */
  gravatarUrl?: string | null;
}
