/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Chambered API
 * An OData and version-compliant API for Chambered inventory tracking.
 * OpenAPI spec version: 1.0
 */
import type { PewPew } from './pewPew';

export interface Caliber {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  alternateNames?: string | null;
  /** @nullable */
  models?: PewPew[] | null;
  id?: number;
  /** @nullable */
  created?: string | null;
  /** @nullable */
  modified?: string | null;
  /** @nullable */
  createdBy?: string | null;
  /** @nullable */
  modifiedBy?: string | null;
}
