/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Chambered API
 * An OData and version-compliant API for Chambered inventory tracking.
 * OpenAPI spec version: 1.0
 */
import type { ChallengePropertiesDtoProperties } from './challengePropertiesDtoProperties';

export interface ChallengePropertiesDto {
  /** @nullable */
  scheme?: string | null;
  /** @nullable */
  redirectUri?: string | null;
  /** @nullable */
  properties?: ChallengePropertiesDtoProperties;
}
