/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Chambered API
 * An OData and version-compliant API for Chambered inventory tracking.
 * OpenAPI spec version: 1.0
 */
import type { ArmoryItem } from './armoryItem';

export interface ChamberedUser {
  /** @nullable */
  firstName?: string | null;
  /** @nullable */
  lastName?: string | null;
  /** @nullable */
  id?: string | null;
  /** @nullable */
  userName?: string | null;
  /** @nullable */
  normalizedUserName?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  normalizedEmail?: string | null;
  emailConfirmed?: boolean;
  /** @nullable */
  passwordHash?: string | null;
  /** @nullable */
  securityStamp?: string | null;
  /** @nullable */
  concurrencyStamp?: string | null;
  /** @nullable */
  phoneNumber?: string | null;
  phoneNumberConfirmed?: boolean;
  twoFactorEnabled?: boolean;
  /** @nullable */
  lockoutEnd?: string | null;
  lockoutEnabled?: boolean;
  accessFailedCount?: number;
  /** @nullable */
  ownedItems?: ArmoryItem[] | null;
  /** @nullable */
  benificiaryItems?: ArmoryItem[] | null;
}
