/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Chambered API
 * An OData and version-compliant API for Chambered inventory tracking.
 * OpenAPI spec version: 1.0
 */

/**
 * Data transfer object containing backup schedule and path configurations.
 */
export interface ConfigurationSectionResponseDto {
  /** Indicates whether automated schedule is active. */
  enabled?: boolean;
  /**
     * The file system directory where backups are saved.
     * @nullable
     */
  backupPath?: string | null;
  /**
     * The CRON notation schedule.
     * @nullable
     */
  cronSchedule?: string | null;
  /** The maximum number of backup archives kept before deletion. */
  retentionCount?: number;
}
