/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Chambered API
 * An OData and version-compliant API for Chambered inventory tracking.
 * OpenAPI spec version: 1.0
 */

export interface CreateApiKeyDto {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  expiresAt?: string | null;
  /** @nullable */
  claims?: string[] | null;
  /** @nullable */
  userId?: string | null;
}
