/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Chambered API
 * An OData and version-compliant API for Chambered inventory tracking.
 * OpenAPI spec version: 1.0
 */
import type { ActionStatDto } from './actionStatDto';
import type { CaliberStatDto } from './caliberStatDto';
import type { RecentActivityDto } from './recentActivityDto';

export interface DashboardStatsDto {
  totalArmoryItems?: number;
  totalRounds?: number;
  totalArmoryValue?: number;
  cumulativeRoundsFired?: number;
  /** @nullable */
  caliberBreakdown?: CaliberStatDto[] | null;
  /** @nullable */
  armoryActionBreakdown?: ActionStatDto[] | null;
  handloadedRounds?: number;
  factoryRounds?: number;
  /** @nullable */
  recentActivities?: RecentActivityDto[] | null;
}
