/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Chambered API
 * An OData and version-compliant API for Chambered inventory tracking.
 * OpenAPI spec version: 1.0
 */
import type { DocumentType } from './documentType';
import type { Product } from './product';

export interface Document {
  /** @nullable */
  title?: string | null;
  type?: DocumentType;
  /** @nullable */
  fileData?: string | null;
  /** @nullable */
  fileName?: string | null;
  /** @nullable */
  contentType?: string | null;
  fileSizeBytes?: number;
  /** @nullable */
  productId?: number | null;
  id?: number;
  /** @nullable */
  created?: string | null;
  /** @nullable */
  modified?: string | null;
  /** @nullable */
  createdBy?: string | null;
  /** @nullable */
  modifiedBy?: string | null;
  product?: Product;
}
