/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Chambered API
 * An OData and version-compliant API for Chambered inventory tracking.
 * OpenAPI spec version: 1.0
 */

export interface EmailConfigurationResponseDto {
  /** @nullable */
  host?: string | null;
  port?: number;
  /** @nullable */
  userName?: string | null;
  hasPassword?: boolean;
  /** @nullable */
  securityOption?: string | null;
  allowInvalidCertificates?: boolean;
  /** @nullable */
  defaultFromAddress?: string | null;
  /** @nullable */
  defaultFromDisplayName?: string | null;
}
