/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Chambered API
 * An OData and version-compliant API for Chambered inventory tracking.
 * OpenAPI spec version: 1.0
 */

/**
 * Represents the resolved favicon file transfer object.
 */
export interface FaveIconDto {
  /**
     * Gets or sets the base64-encoded binary data of the favicon.
     * @nullable
     */
  base64Data?: string | null;
  /**
     * Gets or sets the media content type of the image.
     * @nullable
     */
  contentType?: string | null;
}
