/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Chambered API
 * An OData and version-compliant API for Chambered inventory tracking.
 * OpenAPI spec version: 1.0
 */

export interface FederatedLoginResponseDto {
  isSuccess?: boolean;
  /** @nullable */
  errorMessage?: string | null;
  /** @nullable */
  token?: string | null;
  /** @nullable */
  assignedPermissions?: string[] | null;
}
