/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Chambered API
 * An OData and version-compliant API for Chambered inventory tracking.
 * OpenAPI spec version: 1.0
 */

export type GetArmoryItemDocumentsDownloadAllFromParentIdParams = {
parentId?: number;
select?: string;
expand?: string;
};
