/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Chambered API
 * An OData and version-compliant API for Chambered inventory tracking.
 * OpenAPI spec version: 1.0
 */

export type GetDashboardDashboardStatsParams = {
/**
 * The unique key of the Arsenal. If omitted, defaults to the first available Arsenal.
 */
arsenalId?: number;
'api-version'?: string;
};
