/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Chambered API
 * An OData and version-compliant API for Chambered inventory tracking.
 * OpenAPI spec version: 1.0
 */

export type GetProductsArmoryItemsCountFromKeyParams = {
select?: string;
expand?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};
