/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Chambered API
 * An OData and version-compliant API for Chambered inventory tracking.
 * OpenAPI spec version: 1.0
 */

/**
 * Represents a downloadable asset attached to a GitHub release,
 * simplified for API responses.
 */
export interface GitHubAssetDto {
  /**
     * The file name of the asset.
     * @nullable
     */
  name?: string | null;
  /**
     * The public URL for downloading the asset.
     * @nullable
     */
  browserDownloadUrl?: string | null;
  /** The size of the asset in bytes. */
  size?: number;
  /** The timestamp when the asset was created. */
  createdAt?: string;
  /** The timestamp when the asset was last updated. */
  updatedAt?: string;
}
