/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Chambered API
 * An OData and version-compliant API for Chambered inventory tracking.
 * OpenAPI spec version: 1.0
 */

/**
 * Represents a simplified view of a GitHub user who authored a release
 * or uploaded an associated asset.
 */
export interface GitHubAuthorDto {
  /**
     * The GitHub username.
     * @nullable
     */
  login?: string | null;
  /** The numeric GitHub user identifier. */
  id?: number;
  /**
     * The URL of the user's avatar image.
     * @nullable
     */
  avatarUrl?: string | null;
  /**
     * The public HTML URL for the user's GitHub profile.
     * @nullable
     */
  htmlUrl?: string | null;
}
