/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Chambered API
 * An OData and version-compliant API for Chambered inventory tracking.
 * OpenAPI spec version: 1.0
 */
import type { GitHubAssetDto } from './gitHubAssetDto';
import type { GitHubAuthorDto } from './gitHubAuthorDto';

/**
 * Represents a simplified, API‑friendly view of a GitHub release,
 * suitable for returning to clients without exposing internal GitHub URLs.
 */
export interface GitHubReleaseDto {
  /** The unique numeric identifier for the release. */
  id?: number;
  /**
     * The tag name associated with the release (e.g., `v5.2.0-rc2`).
     * @nullable
     */
  tagName?: string | null;
  /**
     * The display name of the release.
     * @nullable
     */
  name?: string | null;
  /**
     * The release notes or description text.
     * @nullable
     */
  body?: string | null;
  /**
     * The public HTML URL for viewing the release on GitHub.
     * @nullable
     */
  htmlUrl?: string | null;
  /** Indicates whether the release is a draft. */
  draft?: boolean;
  /** Indicates whether the release is marked as a prerelease. */
  prerelease?: boolean;
  /**
     * Indicates whether this release is the newest release
     * according to the server's versioning logic.
     */
  isLatest?: boolean;
  /** The timestamp when the release was created. */
  createdAt?: string;
  /** The timestamp when the release was published. */
  publishedAt?: string;
  author?: GitHubAuthorDto;
  /**
     * A collection of assets attached to the release.
     * @nullable
     */
  assets?: GitHubAssetDto[] | null;
}
