/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Chambered API
 * An OData and version-compliant API for Chambered inventory tracking.
 * OpenAPI spec version: 1.0
 */

export type ItemCondition = typeof ItemCondition[keyof typeof ItemCondition];


export const ItemCondition = {
  NUMBER_0: 0,
  NUMBER_50: 50,
  NUMBER_60: 60,
  NUMBER_70: 70,
  NUMBER_80: 80,
  NUMBER_90: 90,
  NUMBER_95: 95,
  NUMBER_98: 98,
  NUMBER_100: 100,
} as const;
