/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Chambered API
 * An OData and version-compliant API for Chambered inventory tracking.
 * OpenAPI spec version: 1.0
 */
import type { Product } from './product';

export interface Manufacturer {
  id?: number;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  webPageUrl?: string | null;
  /** @nullable */
  phoneNumber?: string | null;
  /** @nullable */
  streetAddress?: string | null;
  /** @nullable */
  city?: string | null;
  /** @nullable */
  stateOrProvince?: string | null;
  /** @nullable */
  postalCode?: string | null;
  /** @nullable */
  country?: string | null;
  /** @nullable */
  product?: Product[] | null;
}
