/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Chambered API
 * An OData and version-compliant API for Chambered inventory tracking.
 * OpenAPI spec version: 1.0
 */

/**
 * Data transfer object defining password complexity criteria.
 */
export interface PasswordPolicyResponseDto {
  /** The minimum character length requirement. */
  minLength?: number;
  /** Indicates whether uppercase characters are mandatory. */
  requireUpper?: boolean;
  /** Indicates whether lowercase characters are mandatory. */
  requireLower?: boolean;
  /** Indicates whether numeric digits are mandatory. */
  requireNumbers?: boolean;
  /** Indicates whether non-alphanumeric characters are mandatory. */
  requireSpecial?: boolean;
}
