/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Chambered API
 * An OData and version-compliant API for Chambered inventory tracking.
 * OpenAPI spec version: 1.0
 */
import type { ActionType } from './actionType';
import type { ArmoryItem } from './armoryItem';
import type { Caliber } from './caliber';
import type { Manufacturer } from './manufacturer';
import type { PewPewCategory } from './pewPewCategory';
import type { ProductDocument } from './productDocument';

export interface PewPew {
  pewPewCategory?: PewPewCategory;
  caliberId?: number;
  actionType?: ActionType;
  isNfaItem?: boolean;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  description?: string | null;
  manufacturerId?: number;
  /** @nullable */
  productType?: string | null;
  /** @nullable */
  partNumber?: string | null;
  /** @nullable */
  sku?: string | null;
  /** @nullable */
  webPageUrl?: string | null;
  id?: number;
  /** @nullable */
  created?: string | null;
  /** @nullable */
  modified?: string | null;
  /** @nullable */
  createdBy?: string | null;
  /** @nullable */
  modifiedBy?: string | null;
  caliber?: Caliber;
  manufacturer?: Manufacturer;
  /** @nullable */
  productDocuments?: ProductDocument[] | null;
  /** @nullable */
  armoryItems?: ArmoryItem[] | null;
}
