/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Chambered API
 * An OData and version-compliant API for Chambered inventory tracking.
 * OpenAPI spec version: 1.0
 */
import type { ActionType } from './actionType';
import type { ArmoryItem } from './armoryItem';
import type { Caliber } from './caliber';
import type { Document } from './document';
import type { Manufacturer } from './manufacturer';
import type { PewPewCategory } from './pewPewCategory';

export interface PewPew {
  pewPewCategory?: PewPewCategory;
  caliberId?: number;
  actionType?: ActionType;
  isNfaItem?: boolean;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  description?: string | null;
  id?: number;
  /** @nullable */
  partNumber?: string | null;
  /** @nullable */
  sku?: string | null;
  manufacturerId?: number;
  /** @nullable */
  webPageUrl?: string | null;
  /** @nullable */
  imageData?: string | null;
  /** @nullable */
  imageContentType?: string | null;
  caliber?: Caliber;
  manufacturer?: Manufacturer;
  /** @nullable */
  documents?: Document[] | null;
  /** @nullable */
  armoryItems?: ArmoryItem[] | null;
}
