/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Chambered API
 * An OData and version-compliant API for Chambered inventory tracking.
 * OpenAPI spec version: 1.0
 */
import type { ArmoryItem } from './armoryItem';
import type { Document } from './document';
import type { Manufacturer } from './manufacturer';

export interface Product {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  description?: string | null;
  id?: number;
  /** @nullable */
  partNumber?: string | null;
  /** @nullable */
  sku?: string | null;
  manufacturerId?: number;
  manufacturer?: Manufacturer;
  /** @nullable */
  webPageUrl?: string | null;
  /** @nullable */
  imageData?: string | null;
  /** @nullable */
  imageContentType?: string | null;
  /** @nullable */
  documents?: Document[] | null;
  /** @nullable */
  armoryItems?: ArmoryItem[] | null;
}
