/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Chambered API
 * An OData and version-compliant API for Chambered inventory tracking.
 * OpenAPI spec version: 1.0
 */

/**
 * API projection for product documents.
 */
export interface ProductDocumentDto {
  id?: number;
  productId?: number;
  /** @nullable */
  type?: string | null;
  /** @nullable */
  fileName?: string | null;
  /** @nullable */
  contentType?: string | null;
  fileSizeBytes?: number;
  isEncrypted?: boolean;
  uploadedAt?: string;
}
