/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Chambered API
 * An OData and version-compliant API for Chambered inventory tracking.
 * OpenAPI spec version: 1.0
 */
import type { Product } from './product';
import type { ProductDocumentType } from './productDocumentType';

export interface ProductDocument {
  type?: ProductDocumentType;
  /** @nullable */
  productId?: number | null;
  /** @nullable */
  contentType?: string | null;
  /** @nullable */
  fileName?: string | null;
  /** @nullable */
  storageKey?: string | null;
  isEncrypted?: boolean;
  fileSizeBytes?: number;
  uploadedAt?: string;
  id?: number;
  /** @nullable */
  created?: string | null;
  /** @nullable */
  modified?: string | null;
  /** @nullable */
  createdBy?: string | null;
  /** @nullable */
  modifiedBy?: string | null;
  product?: Product;
}
