/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Chambered API
 * An OData and version-compliant API for Chambered inventory tracking.
 * OpenAPI spec version: 1.0
 */
import type { ArmoryItem } from './armoryItem';
import type { Manufacturer } from './manufacturer';
import type { ProductDocument } from './productDocument';

export interface Product {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  description?: string | null;
  manufacturerId?: number;
  manufacturer?: Manufacturer;
  /** @nullable */
  productType?: string | null;
  /** @nullable */
  partNumber?: string | null;
  /** @nullable */
  sku?: string | null;
  /** @nullable */
  webPageUrl?: string | null;
  /** @nullable */
  coverImageId?: number | null;
  /** @nullable */
  productDocuments?: ProductDocument[] | null;
  id?: number;
  /** @nullable */
  created?: string | null;
  /** @nullable */
  modified?: string | null;
  /** @nullable */
  createdBy?: string | null;
  /** @nullable */
  modifiedBy?: string | null;
  /** @nullable */
  armoryItems?: ArmoryItem[] | null;
}
