/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Chambered API
 * An OData and version-compliant API for Chambered inventory tracking.
 * OpenAPI spec version: 1.0
 */
import type { ArmoryItem } from './armoryItem';
import type { BatteryType } from './batteryType';
import type { Document } from './document';
import type { LockType } from './lockType';
import type { Manufacturer } from './manufacturer';

export interface Security {
  lockType?: LockType;
  isCapacityLimited?: boolean;
  maxCapacity?: number;
  hasBattery?: boolean;
  batteryType?: BatteryType;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  productType?: string | null;
  /** @nullable */
  partNumber?: string | null;
  /** @nullable */
  sku?: string | null;
  manufacturerId?: number;
  /** @nullable */
  webPageUrl?: string | null;
  /** @nullable */
  imageData?: string | null;
  /** @nullable */
  imageContentType?: string | null;
  id?: number;
  /** @nullable */
  created?: string | null;
  /** @nullable */
  modified?: string | null;
  /** @nullable */
  createdBy?: string | null;
  /** @nullable */
  modifiedBy?: string | null;
  manufacturer?: Manufacturer;
  /** @nullable */
  documents?: Document[] | null;
  /** @nullable */
  armoryItems?: ArmoryItem[] | null;
}
