/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Chambered API
 * An OData and version-compliant API for Chambered inventory tracking.
 * OpenAPI spec version: 1.0
 */

/**
 * Represents a generic OData envelope wrapper for collection responses.
 */
export interface StringODataValue {
  /**
     * Gets or sets the collection value.
     * @nullable
     */
  value?: string[] | null;
}
