/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Chambered API
 * An OData and version-compliant API for Chambered inventory tracking.
 * OpenAPI spec version: 1.0
 */
import type { ArmoryItem } from './armoryItem';
import type { Arsenal } from './arsenal';
import type { Product } from './product';
import type { Vault as __Vault } from './vault';
import type { VaultCategory } from './vaultCategory';

export interface Vault {
  vaultCategory?: VaultCategory;
  /** @nullable */
  parentVaultId?: number | null;
  /** @nullable */
  encryptedPasscode?: string | null;
  /** @nullable */
  encryptionIv?: string | null;
  /** @nullable */
  passcodeHint?: string | null;
  /** @nullable */
  backupKeyLocation?: string | null;
  /** @nullable */
  batteryLastChangedDate?: string | null;
  /** @nullable */
  batteryExpirationDate?: string | null;
  /** @nullable */
  productId?: number | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  description?: string | null;
  arsenalId?: number;
  currentCapacity?: number;
  hasDehumidifier?: boolean;
  /** @nullable */
  dehumidifierLastServiced?: string | null;
  /** @nullable */
  targetMaxHumidityPercent?: number | null;
  id?: number;
  /** @nullable */
  created?: string | null;
  /** @nullable */
  modified?: string | null;
  /** @nullable */
  createdBy?: string | null;
  /** @nullable */
  modifiedBy?: string | null;
  parentVault?: __Vault;
  /** @nullable */
  childVaults?: Vault[] | null;
  /** @nullable */
  armoryItems?: ArmoryItem[] | null;
  product?: Product;
  arsenal?: Arsenal;
}
