<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Title>Chambered.Core</Title>
    <Version>5.2.1</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="5.0.17" />
  </ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Chambered.Data\Chambered.Data.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Extensions\" />
	</ItemGroup>

</Project>
