<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <SpaRoot>client\</SpaRoot>
    <SpaProxyServerUrl>http://localhost:5173</SpaProxyServerUrl>
    <SpaProxyLaunchCommand>npm run dev</SpaProxyLaunchCommand>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
    <Version>5.2.1</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.OData" Version="8.1.0" />
    <PackageReference Include="Asp.Versioning.OData.ApiExplorer" Version="8.1.0" />
    <PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="Cronos" Version="0.13.0" />
    <PackageReference Include="Microsoft.AspNetCore.OData" Version="9.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.SpaProxy" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="9.0.2" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BeatnikToolKit.GitVersioning\BeatnikToolKit.GitVersioning.csproj" />
    <ProjectReference Include="..\Chambered.Infrastructure\Chambered.Infrastructure.csproj" />
  </ItemGroup>

</Project>
